name: Convert Blogger XML to MovableType Format

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Rename uploaded file to blogger.xml
        run: mv blog-06-23-2025.xml blogger.xml

      - name: Run conversion script
        run: python convert.py

      - name: Upload converted file
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: export.txt
