name: Convert Blogger XML to MT Format

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 依存ライブラリがあればここに記述。なければスキップ可

      - name: Run conversion script
        run: python convert.py blogger.xml output.txt

      - name: Upload converted MT file
        uses: actions/upload-artifact@v4
        with:
          name: mt-converted-file
          path: output.txt
