name: Convert Blogger to MT Format

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run conversion script
        run: python convert.py

      - name: Upload converted file
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: export.txt
