name: Convert Blogger XML to MT Format

on:
    workflow_dispatch:    # ← これを追加
  push:
    paths:
      - 'blogger.xml'
      - 'convert.py'
      - '.github/workflows/convert.yml'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:

  push:
    paths:
      - 'blogger.xml'
      - 'convert.py'
      - '.github/workflows/convert.yml'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run convert.py
        run: python convert.py

      - name: Upload result file
        uses: actions/upload-artifact@v4
        with:
          name: export
          path: export.txt

