name: Convert Blogger XML to MT Format

on:
  workflow_dispatch:
    inputs:
      input-file:
        description: 'Upload Blogger XML file'
        required: true
        type: file

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Upload input file
      uses: actions/upload-artifact@v4
      with:
        name: blogger-xml
        path: ${{ github.event.inputs['input-file'] }}

    - name: Download input file
      uses: actions/download-artifact@v3
      with:
        name: blogger-xml
        path: ./ 

    - name: Run conversion script
      run: |
        python3 convert.py blogger.xml export.txt

    - name: Upload converted MT file
      uses: actions/upload-artifact@v4
      with:
        name: mt-export
        path: export.txt
