name: Convert Blogger to MT

on:
  push:
    paths:
      - 'blogger.xml'
      - 'convert.py'
      - '.github/workflows/convert.yml'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run converter
        run: python convert.py

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: export-txt
          path: export.txt
