name: Convert Blogger XML to MT Format

on:
  workflow_dispatch:
    inputs:
      blogger-xml:
        description: 'Upload Blogger XML file'
        required: true
        type: file

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload Blogger XML
      uses: actions/upload-artifact@v4
      with:
        name: blogger-xml
        path: ${{ github.event.inputs.blogger-xml }}

    - name: Download Blogger XML
      uses: actions/download-artifact@v4
      with:
        name: blogger-xml
        path: .

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run convert script
      run: python3 convert.py blogger.xml export.txt

    - name: Upload converted MT file
      uses: actions/upload-artifact@v4
      with:
        name: mt-export
        path: export.txt
